# Generated by Django 2.1.7 on 2019-05-05 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extra',
            name='extra_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(blank=True, choices=[('ongoing', 'ongoing'), ('cancelled', 'cancelled'), ('ready', 'ready'), ('done', 'done')], default='ongoing', max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='image_path',
            field=models.ImageField(blank=True, default='menu_images/default.png', null=True, upload_to='menu_images'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='rating',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='order_menu',
            name='quantity',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='close_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='image_path',
            field=models.ImageField(blank=True, default='restaurant_images/default.png', null=True, upload_to='restaurant_images'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='open_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='rating',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='status',
            field=models.CharField(choices=[('close', 'close'), ('open', 'open')], default='close', max_length=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='image_path',
            field=models.ImageField(blank=True, default='profile_images/default.png', null=True, upload_to='profile_images'),
        ),
    ]
